# Generated by Django 5.1.6 on 2025-03-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together=set(),
        ),
    ]
